- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 Instance
      ec2: 
        instance_type: t2.micro
        image: ami-0574da719dca65348
        region: us-east-1
        key_name: dasha
        vpc_subnet_id: subnet-0cfdb2b07721723a8
        group: eshop
        count: 1
        assign_public_ip: yes
        wait: yes
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        security_token: "{{ session_token }}"
      register: ec2
    - name: Add instance host to group
      add_host: 
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"
    - name: Wait for ssh connection
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection: 
        delay: 30
        timeout: 300
      loop: "{{ ec2.instances }}"

- name: Configure EC2
  hosts: launched
  connection: ssh

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
      become: yes

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
      become: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: yes

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      become: yes

    - name: Install Docker Module for Python
      pip:
        name: docker
      become: yes

#    - name: Just force systemd to reread configs (2.4 and above)
#      ansible.builtin.systemd:
#        daemon_reload: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Start Docker on startup
      shell: systemctl enable docker
      become: yes
    - name: Set rights to Docker
      shell: usermod -a -G docker ubuntu
      become: yes

    - name: Get project files from GIT
      git: 
        repo: 'https://github.com/dariatutynina/4IT572_docker.git'
        dest: ./app
    - name: Build docker image
      shell: cd app && docker build -t myeshop:latest .
      become: yes
    - name: Run eshop
      shell: docker run -p 80:3000 myeshop
      async: 45
      poll: 0
      become: yes
    - wait_for: 
        port:
          80
